alias untar "tar -xvzf"
alias ls "ls --color=auto"
alias ll "ls -l --color=auto"
alias grep "grep --color=auto"
alias upgrade "sudo pacman -Syu"
alias update "sudo pacman -Syu"
alias dots "cd ~/three-dotfiles && git status"
